require 'rubygems' unless defined? Gem # rubygems is only needed in 1.8
require "bundler/setup"

require 'fileutils'
require 'rspec/core/rake_task'

desc "Run all specs"
RSpec::Core::RakeTask.new(:spec) do |t|
	t.fail_on_error = false
	t.pattern = 'spec/*_spec.rb'
    t.rspec_opts = ['--colour', '--backtrace']
end

task :default => :spec